# Generated by Django 3.1.4 on 2020-12-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('m2', models.FloatField(max_length=10)),
                ('habitaciones', models.IntegerField()),
                ('banhos', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
