# Generated by Django 3.1.4 on 2020-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('red_social', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
